function h = createPauseButton
h = figure(1);
WinOnTop(h);
set(h,'MenuBar','none','Units','Normalized');
set(h,'Position',[0.9 0.05 0.05 0.05]);
uicontrol(... % Button for updating selected plot
    'Parent', h, ...
    'Units','normalized',...
    'HandleVisibility','callback', ...
    'Position',[0.05 0.05 0.9 0.9],...
    'String','Pause Simulation',...
    'BackgroundColor',[1 0.6 0.6],...
    'Callback', 'eval(''keyboard'')');